### ISSUE TITLE
fix bugs

### ISSUE THREAD

**Issue by mrprohack** [tamilanmkv/translate_cliper#2]
from googletrans import Translator
import argparse
import clipboard
import json
import re
import os

translator = Translator()

def translate(english_word, en_output, es_output, key):
    translation = translator.translate(english_word, dest="es")
    key_name = re.sub(r'[^\w\s]', '', english_word).replace(" ", "_").lower()

    # Load English translation data
    with open(en_output, 'r') as json_file_en:
        en_data = json.load(json_file_en)

    # Update English translation data
    with open(en_output, 'w') as en_file:
        if key:
            new_key = key.replace(' ', '_').lower()
            if new_key not in en_data['translation']:
                en_data['translation'][new_key] = {}
            en_data['translation'][new_key][key_name] = english_word
        else:
            en_data['translation'][key_name] = english_word
        json.dump(en_data, en_file, ensure_ascii=False)

    # Load Spanish translation data
    with open(es_output, 'r') as json_file_es:
        es_data = json.load(json_file_es)

    # Update Spanish translation data
    with open(es_output, 'w') as es_file:
        if key:
            new_key = key.replace(' ', '_').lower()
            if new_key not in es_data['translation']: 
                es_data['translation'][new_key] = {}
            es_data['translation'][new_key][key_name] = translation.text
        else:
            es_data['translation'][key_name] = translation.text
        json.dump(es_data, es_file, ensure_ascii=False)

    print("English word:", english_word)
    print("Spanish word:", translation.text)
    clipboard.copy(key_name)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-en", "--en_output", help="Save output to a file in JSON format in English")
    parser.add_argument("-es", "--es_output", help="Save output to a file in JSON format in Spanish")
    parser.add_argument("-k", "--key", help="JSON key name for inserting the word")
    args = parser.parse_args()

    if args.en_output:
        if not os.path.exists(args.en_output):
            with open(args.en_output, 'w') as en_file:
                json.dump({'translation': {}}, en_file)

    if args.es_output:
        if not os.path.exists(args.es_output):
            with open(args.es_output, 'w') as es_file:
                json.dump({'translation': {}}, es_file)

    while True:
        english_word = input("Enter a word to translate: ")
        if english_word == "exit()":
            print("Exiting...")
            break
        translate(english_word, args.en_output, args.es_output, args.key)

**Comment by mrprohack** [comment]
update a code

**Comment by tamilanmkv** [comment]
Thanks for you updats
